### ISSUE TITLE
Add SwiftLint

### ISSUE THREAD

**Issue by nngenov** [paysafegroup/paysafe_sdk_ios#8]

**Comment by nngenov** [comment]
@rradenkov-paysafe @itskoBits @tsstoyanova Any suggestions for the rules ?

**Comment by rradenkov-paysafe** [comment]
I can suggest something basic like this. Not sure how many issues will come from it though:
```yaml
disabled_rules: # rule identifiers to exclude from running
  - shorthand_operator
  - redundant_string_enum_value
  - unused_optional_binding

opt_in_rules: # some rules are only opt-in
  - collection_alignment
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument

force_unwrapping:
    severity: error

implicitly_unwrapped_optional:
    severity: error

line_length:
    ignores_comments: true

```
